### ISSUE TITLE
Documentation switcher broken

### ISSUE THREAD

**Issue by RobPasMue** [ansys/pymechanical-stubs#8]
We should be deploying the docs through our Ansys actions, since they are the ones handling the multi-version scheme:

```yml
    name: Upload release documentation
    if: github.event_name == 'push' && contains(github.ref, 'refs/heads/release')
    runs-on: ubuntu-latest
    needs: [doc-build]
    steps:
      - name: Deploy the stable documentation
        uses: ansys/actions/doc-deploy-stable@v4
        with:
          cname: ${{ env.DOCUMENTATION_CNAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
```

However, this project is a bit special... Our versions should be the ones for the API versions.

* I propose we adapt the current workflow to use "common" env variables whenever possible.
* We will then have release branches for the various mechanical API branches.

```
release/23.1
release/23.2
...
```

* And they will all be coming out from main.
* Each of these branches will then have to adapt their env variables and container used.
* No docs will be published from the main branch (and thus, no dev target will be available)
